### ISSUE TITLE
New project list for sushack 3?

### ISSUE THREAD

**Issue by benfoxall** [sushack/sushack.github.io#34]
Last year you made #18 to point to plonk ideas down.  Do we need another one for sushack 3?

- [x] create a new issue
- [x] link it on [the site](https://github.com/sushack/sushack.github.io/blob/master/_includes/section_2.html#L9)

I've labelled issues on this project to be `sushack-2` - hope that's okay

**Comment by omgmog** [comment]
Sounds like a plan. I'll do these things..
