### ISSUE TITLE
C-A-R-D-B-O-A-R-D

### ISSUE THREAD

**Issue by omgmog** [sushack/sushack.github.io#40]
From my original comment in https://github.com/sushack/sushack.github.io/issues/35#issuecomment-107233073
>  I'm interested in hacking around with real-space motion/orientation and mobile phones, using the Google Cardboard stuff (https://www.google.com/get/cardboard/).
>
> So I've ordered a couple of Google Cardboard kits from Amazon, one [cardboard](http://www.amazon.co.uk/gp/product/B00V7Z2XM0), one [plastic](http://www.amazon.co.uk/gp/product/B00ROW1SS0), they should arrive in plenty of time.
>
> Regarding making this a "sustainability" thing, we could do something like mashing up google street view and some map data source? Oxford Flood Network in 3d?! who knows, should be fun.
>
> In the mean time, I'll probably brush up on my device orientation knowledge, and anybody who would like to join in should too!

**Comment by omgmog** [comment]
So Ive now received the Plastic kit, and I'm pretty impressed so far. Still buzzing with ideas, perhaps involving augmenting the camera feed with some real time data, all in the browser.

**Comment by benfoxall** [comment]
Fantastic! I'm really psyched about getting mine through (thanks for the inspiration).

Augmenting the camera feed would be cool.  We've got a glass too; totally different stack I guess - but I guess it might be cool.

If it's web/getUserMedia based - I've got a bit of experience with https://github.com/jcmellado/js-aruco - which we could use to pick out particular places/objects easily.

**Comment by omgmog** [comment]
That's a cool library. Really depends on the kind of AR we want to do:

1. Responding to an object to anchor projected things on a camera feed
2. Use the device orientation, location, etc. and just overlay some real world data, such as flood network stuff, or trains, or what ev's.

The first one is cool, but we would probably need to think hard for way to make it remotely susty.

The second can be cool depending on the data, and how big/little a problem the lack of accuracy, or orientation "drift" is when looking around.

On a sort of related note, there's a cool Android app I've had some fun with called [Glitcher VR](https://play.google.com/store/apps/details?id=net.dystopiazero.theglitcher&hl=en_GB) which does some nice video feed effects. It would be cool to be able to reproduce some of the filters/effects that it has, but in purely web/getUserMedia/canvas stuff ala http://html5demos.com/gum-canvas

**Comment by omgmog** [comment]
OH OH I just had a cooler idea, as we'll be using a couple of devices.. how about WebRTC beaming the feed from each others devices to each other, that would be a real mind f***.

Could even have something like

`Person a`:
- is the video capture device
- on their screen they get visual feedback of the directions to move, received from `Person b`.

`Person b`:
- is the video playback device
- as they move their head, they send directional commands to `Person a`.

**Comment by omgmog** [comment]
This thread needs more @LuRsT :thought_balloon:

**Comment by AverageMarcus** [comment]
I'm so in! :+1:

**Comment by LuRsT** [comment]
Hi I'm here :+1:

**Comment by omgmog** [comment]
Great! As I mentioned, I'll have two cardboard units with me, so all we'll need is our phones and some WebRTC and html5 video/canvas knowledge!

**Comment by benfoxall** [comment]
@AverageMarcus has a cardboard now! Also anyone is welcome to borrow mine if you want a bunch of them (I'm not going to be able to make it if #43 gets merged).

I've been thinking a lot about sensor fusion; with the web based approach you're limited to the orientation sensors on the phone - where you could also be making use of the optic flow from the camera to work out how your position is changing (I'm not sure, but I'd imagine the native library does this).

Not sure how it would relate to sustainability though…!

Also, if you're interested in augmented reality - @peterjwest might want to get involved.

**Comment by omgmog** [comment]
so.. if we don't merge #43, you'll be coming?

![](http://media.giphy.com/media/aI7Ret2L4hnMI/giphy.gif)

**Comment by omgmog** [comment]
Saving this for later, http://www.html5rocks.com/en/tutorials/device/orientation/
